apiVersion: v1
kind: Service
metadata:
  name: mgcloud-service
  labels:
    app: mgcloud-api
spec:
  type: ClusterIP
  selector:
    app: mgcloud-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000