# Generated by Django 4.1.3 on 2024-09-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0013_delete_filelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('filesize', models.CharField(max_length=20)),
                ('filetype', models.CharField(max_length=20)),
                ('relativepath', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('mgsecure', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('sharedwith', models.ManyToManyField(blank=True, related_name='sharedwith', to='api.users')),
            ],
        ),
    ]
