# Generated by Django 4.1.3 on 2024-09-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelog',
            old_name='mgsecure',
            new_name='isFavourite',
        ),
        migrations.RenameField(
            model_name='filelog',
            old_name='shared',
            new_name='isMgsecure',
        ),
        migrations.AddField(
            model_name='filelog',
            name='isShared',
            field=models.BooleanField(default=False),
        ),
    ]
