# Generated by Django 4.1.3 on 2024-09-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_filelog'),
        ('core', '0002_rename_mgsecure_filelog_isfavourite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirName', models.CharField(max_length=50)),
                ('fileCount', models.PositiveIntegerField()),
                ('diskSize', models.CharField(max_length=50)),
                ('createdOn', models.DateField()),
                ('isSecure', models.BooleanField()),
                ('passCode', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('parentDir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.directorylog')),
            ],
        ),
    ]
