# Generated by Django 4.1.3 on 2024-09-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_filelog'),
        ('core', '0003_directorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorylog',
            name='isSubdir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directorylog',
            name='fileCount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='directorylog',
            name='isSecure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directorylog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='directorylog',
            name='parentDir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.directorylog'),
        ),
        migrations.AlterField(
            model_name='directorylog',
            name='passCode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
