# Generated by Django 4.1.3 on 2024-09-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_directorylog_parentdir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorylog',
            name='passCode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
