# Generated by Django 4.1.3 on 2024-09-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_directorylog_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='inDirectory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.directorylog'),
        ),
    ]
