# Generated by Django 4.1.3 on 2024-10-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_filelog_indirectory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
