# Generated by Django 4.1.3 on 2024-06-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'MGCloud User', 'verbose_name_plural': 'MGCloud Users'},
        ),
    ]
