# Generated by Django 4.1.3 on 2024-07-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_app_session_users_session_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
