# Generated by Django 4.1.3 on 2024-09-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_users_firstname_users_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
