# Generated by Django 4.1.3 on 2024-09-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_filelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
    ]
