# Generated by Django 4.1.3 on 2024-09-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_filelog_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileLog',
        ),
    ]
