# Generated by Django 4.1.3 on 2024-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_filelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dropbox_access',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='google_access',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='onedrive_access',
            field=models.TextField(blank=True, null=True),
        ),
    ]
